import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'exchange',
        path: '/exchange',
        title: 'Exchange',
        translateKey: 'nav.exchange',
        icon: 'exchange',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'inbox',
        path: '/inbox',
        title: 'Inbox',
        translateKey: 'nav.inbox',
        icon: 'inbox',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'deposit',
        path: '',
        title: 'Deposit',
        translateKey: 'nav.deposit.deposit',
        icon: 'deposit',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'deposit.crypto',
                path: '/deposit/crypto',
                title: 'Crypto',
                translateKey: 'nav.deposit.crypto',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
             {
                key: 'deposit.creditCard',
                path: '/deposit/card',
                title: 'Credit Card',
                translateKey: 'nav.deposit.creditCard',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'deposit.bank',
                path: '/deposit/bank-details',
                title: 'Bank Transfer',
                translateKey: 'nav.deposit.bank',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
           
        ],
    },
    {
        key: 'withdrawal',
        path: '',
        title: 'Withdrawal',
        translateKey: 'nav.withdrawal.withdrawal',
        icon: 'withdrawal',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'withdrawal.crypto',
                path: '/withdrawal/crypto',
                title: 'Crypto',
                translateKey: 'nav.withdrawal.crypto',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'withdrawal.bank',
                path: '/withdrawal/bank',
                title: 'Bank Transfer',
                translateKey: 'nav.withdrawal.bank',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'transaction',
        path: '/transactions',
        title: 'Transaction',
        translateKey: 'nav.transaction',
        icon: 'transaction',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },

    {
        key: 'invoice',
        path: '/invoice',
        title: 'Invoice',
        translateKey: 'nav.invoice',
        icon: 'invoice',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },

    {
        key: 'Viewticket',
        path: '/view-ticket',
        title: 'Support Tickets',
        translateKey: 'nav.Viewticket',
        icon: 'Viewticket',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
]

export default navigationConfig
