// app/faq/page.tsx
'use client'

import { useState } from 'react';
import { FaChevronDown, FaChevronUp } from 'react-icons/fa';

const faqItems = [
  {
    question: "Is there any transaction limit? What is the maximum/minimum amount of the withdrawal transaction?",
    answer: "The minimum and maximum withdrawal amounts differ and are displayed on the page when placing an order.",
    category: "Transactions"
  },
  {
    question: "What is the trading fee?",
    answer: "The fee for your transaction will be displayed before you execute the order.",
    category: "Trading"
  },
  {
    question: "When my deposit order will be processed?",
    answer: "Please wait until your funds are automatically credited to your account. In case of any problems, our support team will contact you.",
    category: "Transactions"
  },
  {
    question: "Where can I see the history of my orders?",
    answer: "You can view your transaction history on the Transactions page in main menu.",
    category: "Trading"
  },
  {
    question: "Can I cancel an Order?",
    answer: "Yes, you can cancel orders that have not yet been accepted. Please contact our support team and describe your problem. Note that once an order is executed, it cannot be canceled.",
    category: "Trading"
  },
  {
    question: "I made a deposit several days ago, but it hasn't been received. What do I do?",
    answer: "Please send us the transaction details and we will investigate the issue.",
    category: "Transactions"
  },
  {
    question: "What is two-factor authentication?",
    answer: "Two-factor authentication adds an extra layer of security to your account. Besides your password, you will need a 6-digit authentication code generated by an app that changes every 30 seconds. We strongly recommend enabling this feature to protect your account from unauthorized access.",
    category: "Security"
  },
  {
    question: "Is it safe to use exchange?",
    answer: "Absolutely! We prioritize the security of our clients' personal data and assets. We use advanced security methods, including two-factor authentication and Anti-Phishing measures. Over 95% of all currency is stored in cold wallets. Our Web Application Firewall (WAF) detects and blocks hacker attacks to ensure the security of our exchange.",
    category: "Security"
  },
  {
    question: "What if I lost the code/key to two-factor authentication?",
    answer: "Contact our support team for assistance",
    category: "Security"
  },
  {
    question: "How to enable two-factor authentication?",
    answer: "Download the Google Authenticator app from the Play Store or App Store. Sign in to your account. Scan the QR code in the app or enter the code manually. After you connect your account to the authenticator, enter the authentication code in the '2FA code' field. After successful confirmation of the code, 2FA will be activated.",
    category: "Security"
  },
  {
    question: "How long does it take to receive a response from the support team? How does it work?",
    answer: "Our customer support team is available 24/7, 365 days a year. If you have questions, suggestions, or issues, our specialists are ready to assist you. We strive to reply as soon as possible.",
    category: "Support"
  },
  {
    question: "How do I replenish my balance?",
    answer: "Find the 'Deposit' item in the main menu and choose a convenient method. Or create a quick crypto deposit using the form on the 'Dashboard' page",
    category: "Transactions"
  },
  {
    question: "How do I cancel a withdrawal request?",
    answer: "Contact our support team for assistance, and we will do our best to help.",
    category: "Transactions"
  },
  {
    question: "On what terms are withdrawal requests processed?",
    answer: "Withdrawals are initiated at different times depending on the type of transaction fee selected.",
    category: "Transactions"
  },
  {
    question: "How to make a withdrawal?",
    answer: "Go to the 'Output' tab and select the type that suits you. After filling in all the necessary data, click the 'Submit' button and your withdrawal request will be generated.",
    category: "Transactions"
  },
  {
    question: "Can I delete my account?",
    answer: "Deleting your account is not available. However, you can block your account. To do this, create a support ticket. Go to Support in the main menu to create a ticket.",
    category: "Account"
  },
  {
    question: "How to log in to your account?",
    answer: "Navigate to /Sign In. Enter your e-mail address, password, then click the Sign In button. You are now logged into your account and can proceed to make a deposit or start trading. We also recommend enabling two-factor authentication for enhanced security.",
    category: "Account"
  },
  {
    question: "What is cryptocurrency?",
    answer: "Cryptocurrency is a form of digital currency that employs cryptography to secure transactions, which are digitally recorded on a distributed ledger such as a blockchain. Transactions recorded on a distributed ledger are called 'on-chain' transactions, whereas those not recorded on the ledger are referred to as 'off-chain' transactions.",
    category: "General"
  }
];

// Get unique categories for filtering
const categories = ["All", ...Array.from(new Set(faqItems.map(item => item.category)))];

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const [selectedCategory, setSelectedCategory] = useState<string>('All');

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const filteredFAQs = selectedCategory === 'All' 
    ? faqItems 
    : faqItems.filter(item => item.category === selectedCategory);

  return (
    <div className="min-h-screen bg-gray-900">
      {/* Main Content */}
      <div className="container mx-auto px-4 py-8">
        {/* Category Filter */}
        <div className="mb-8">
          <div className="flex flex-wrap gap-2 justify-center">
            {categories.map((category) => (
              <button
                key={category}
                onClick={() => {
                  setSelectedCategory(category);
                  setOpenIndex(null); // Close any open FAQ when changing category
                }}
                className={`px-4 py-2 rounded-full text-sm font-medium transition-colors ${
                  selectedCategory === category
                    ? 'bg-blue-600 text-white'
                    : 'bg-gray-800 text-gray-300 hover:bg-gray-700'
                }`}
              >
                {category}
                {category !== 'All' && (
                  <span className="ml-1 text-xs bg-gray-700 px-2 py-0.5 rounded-full">
                    {faqItems.filter(item => item.category === category).length}
                  </span>
                )}
              </button>
            ))}
          </div>
        </div>

        {/* FAQ List */}
        <div className="max-w-3xl mx-auto space-y-3">
          {filteredFAQs.map((item, index) => (
            <div
              key={index}
              className="bg-gray-800 rounded-lg overflow-hidden"
            >
              <button
                onClick={() => toggleFAQ(index)}
                className="w-full px-5 py-4 text-left flex justify-between items-center hover:bg-gray-750 transition-colors"
              >
                <div>
                  <h3 className="font-semibold text-white text-left">
                    {item.question}
                  </h3>
                  <div className="flex items-center gap-2 mt-1">
                    <span className="text-xs px-2 py-1 bg-gray-700 text-gray-300 rounded">
                      {item.category}
                    </span>
                  </div>
                </div>
                <div className="text-gray-400 flex-shrink-0 ml-4">
                  {openIndex === index ? (
                    <FaChevronUp />
                  ) : (
                    <FaChevronDown />
                  )}
                </div>
              </button>
              
              {openIndex === index && (
                <div className="px-5 pb-4 pt-2 border-t border-gray-700">
                  <p className="text-gray-300 whitespace-pre-line">
                    {item.answer}
                  </p>
                </div>
              )}
            </div>
          ))}
        </div>

       
      </div>
    </div>
  );
}